"""add: Signal table

Revision ID: 67a73e05a325
Revises: 6182d3586094
Create Date: 2026-05-19 04:50:28.263193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.storage.types  # UtcDateTime 커스텀 타입 참조용


# revision identifiers, used by Alembic.
revision: str = '67a73e05a325'
down_revision: Union[str, Sequence[str], None] = '6182d3586094'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', app.storage.types.UtcDateTime(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('target', sa.String(length=256), nullable=False),
    sa.Column('applied_rule', sa.String(length=64), nullable=False),
    sa.Column('combined_score', sa.Integer(), nullable=False),
    sa.Column('weight_sum', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('supporting_log_ids', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('signal_log_id', sa.Integer(), nullable=False),
    sa.Column('user_status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_at', app.storage.types.UtcDateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signal_signal_log_id'), 'signal', ['signal_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_signal_signal_log_id'), table_name='signal')
    op.drop_table('signal')
    # ### end Alembic commands ###
